x-postgres-primary-common:
  &postgres-primary-common
  image: postgres:15
  networks:
    - app
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
  command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

x-postgres-replica-common:
  &postgres-replica-common
  image: postgres:15
  networks:
    - app
  command: >
    bash -c "
      PGPASSWORD=postgres psql -U postgres -c \"SELECT pg_create_physical_replication_slot('replication_slot');\";  
      rm -rf /var/lib/postgresql/data/* 
      pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot; 
      chown -R postgres:postgres /var/lib/postgresql/data && chmod 0700 /var/lib/postgresql/data; 
      su postgres -c 'postgres -c config_file=/etc/postgresql/postgresql.conf'; 
    "

services:

  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - app


  config-server:
    build: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8888" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  discovery-server:
    build: discovery-server
    container_name: discovery-server
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
    networks:
      - app
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8761" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  gateway:
    build: gateway
    networks:
      - app
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - DISCOVERY_SERVER=${DISCOVERY_SERVER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      order-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s


  order-service:
    build: order-service
    networks:
      - app
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - DISCOVERY_SERVER=${DISCOVERY_SERVER}
      - PRIMARY_DB_URL=jdbc:postgresql://order-service-primary-db:5432/postgres
      - REPLICA_DB_URL=jdbc:postgresql://order-service-replica-db:5432/postgres
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      order-service-replica-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  inventory-service:
    build: inventory-service
    networks:
      - app
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - DISCOVERY_SERVER=${DISCOVERY_SERVER}
      - PRIMARY_DB_URL=jdbc:postgresql://inventory-service-primary-db:5432/postgres
      - REPLICA_DB_URL=jdbc:postgresql://inventory-service-replica-db:5432/postgres
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      inventory-service-replica-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  auth-service:
    build: auth-service
    networks:
      - app
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - DISCOVERY_SERVER=${DISCOVERY_SERVER}
      - PRIMARY_DB_URL=jdbc:postgresql://auth-service-primary-db:5432/postgres
      - REPLICA_DB_URL=jdbc:postgresql://auth-service-replica-db:5432/postgres
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      auth-service-replica-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  payment-service:
    build: payment-service
    networks:
      - app
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - DISCOVERY_SERVER=${DISCOVERY_SERVER}
      - PRIMARY_DB_URL=jdbc:postgresql://payment-service-primary-db:5432/postgres
      - REPLICA_DB_URL=jdbc:postgresql://payment-service-replica-db:5432/postgres
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_API_SECRET=${STRIPE_API_SECRET}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      payment-service-replica-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  notification-service:
    build: notification-service
    networks:
      - app
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - DISCOVERY_SERVER=${DISCOVERY_SERVER}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  order-service-primary-db:
    <<: *postgres-primary-common
    container_name: order-service-primary-db
    ports:
      - "5432:5432"
    volumes:
      - order-service-primary-data:/var/lib/postgresql/data
      - ./pg/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg/primary/init-scripts:/docker-entrypoint-initdb.d


  order-service-replica-db:
    <<: *postgres-replica-common
    container_name: order-service-replica-db
    depends_on:
      order-service-primary-db:
        condition: service_healthy
    volumes:
      - ./pg/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - order-service-replica-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=replicator
      - PGPASSWORD=replicator_password
      - PGHOST=order-service-primary-db



  inventory-service-primary-db:
    <<: *postgres-primary-common
    container_name: inventory-service-primary-db
    ports:
      - "5433:5432"
    volumes:
      - inventory-service-primary-data:/var/lib/postgresql/data
      - ./pg/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg/primary/init-scripts:/docker-entrypoint-initdb.d


  inventory-service-replica-db:
    <<: *postgres-replica-common
    container_name: inventory-service-replica-db
    volumes:
      - ./pg/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - inventory-service-replica-data:/var/lib/postgresql/data
    depends_on:
      inventory-service-primary-db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=replicator
      - PGPASSWORD=replicator_password
      - PGHOST=inventory-service-primary-db


  auth-service-primary-db:
    <<: *postgres-primary-common
    container_name: auth-service-primary-db
    ports:
      - "5434:5432"
    volumes:
      - auth-service-primary-data:/var/lib/postgresql/data
      - ./pg/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg/primary/init-scripts:/docker-entrypoint-initdb.d


  auth-service-replica-db:
    <<: *postgres-replica-common
    container_name: auth-service-replica-db
    volumes:
      - ./pg/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - auth-service-replica-data:/var/lib/postgresql/data
    depends_on:
      auth-service-primary-db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=replicator
      - PGPASSWORD=replicator_password
      - PGHOST=auth-service-primary-db


  payment-service-primary-db:
    <<: *postgres-primary-common
    container_name: payment-service-primary-db
    ports:
      - "5435:5432"
    volumes:
      - payment-service-primary-data:/var/lib/postgresql/data
      - ./pg/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg/primary/init-scripts:/docker-entrypoint-initdb.d


  payment-service-replica-db:
    <<: *postgres-replica-common
    container_name: payment-service-replica-db
    volumes:
      - ./pg/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - payment-service-replica-data:/var/lib/postgresql/data
    depends_on:
      payment-service-primary-db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGUSER=replicator
      - PGPASSWORD=replicator_password
      - PGHOST=payment-service-primary-db


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  order-service-primary-data:
    driver: local
  order-service-replica-data:
    driver: local
  inventory-service-primary-data:
    driver: local
  inventory-service-replica-data:
    driver: local
  auth-service-primary-data:
    driver: local
  auth-service-replica-data:
    driver: local
  payment-service-primary-data:
    driver: local
  payment-service-replica-data:
    driver: local
  notification-service-primary-data:
    driver: local
  notification-service-replica-data:
    driver: local
  rabbitmq-data:
    driver: local


networks:
  app:
    driver: bridge