# OpenAPI Specification for Payment Service
openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: API for processing payments in the Order Management System.
servers:
  - url: http://payment-service:8080
    description: Payment Service base URL
paths:
  /api/v1/stripe/payment-intent:
    post:
      summary: Process card payment for order
      description: Initiates a card payment for a specific order.
      operationId: processCardPayment
      tags:
        - Stripe
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the order to process payment
        - name: amount
          in: query
          schema:
            type: integer
            format: int64
          required: true
          description: Amount to charge in the smallest currency unit (e.g., cents)
      responses:
        '200':
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientSecret:
                    type: string
        '401':
          description: Unauthorized
      security:
        - BearerAuth: []

  /api/v1/stripe/webhook:
    post:
      summary: Stripe webhook endpoint (internal)
      description: |
        Endpoint for handling Stripe webhook events.
        **Internal use only** — should not be called externally.
      operationId: handleStripeWebhook
      tags:
        - Stripe
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - name: Stripe-Signature
          in: header
          required: true
          schema:
            type: string
          description: Stripe signature header used to verify the webhook payload
      responses:
        '200':
          description: Webhook received and processed
        '400':
          description: Invalid webhook signature or payload
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
