# OpenAPI Specification for Payment Service
openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: API for processing payments in the Order Management System.
servers:
  - url: http://payment-service:8080
    description: Payment Service base URL
paths:
  /payments:
    post:
      summary: Process card payment for order
      description: Initiates a card payment for a specific order.
      operationId: processCardPayment
      tags:
        - Payments
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the order to process payment format
        - name: totalAmount
          in: query
          schema:
            type: integer
            format: int64
          required: true 
      responses:
        '200':
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          description: Invalid payment details
        '401':
          description: Unauthorized
        '404':
          description: Order not found
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Payment:
      type: object
      properties:
        paymentId:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        amount:
          type: number
          format: double
        status:
          type: string
          enum: [PENDING, SUCCESSFUL, FAILED]
        createdAt:
          type: string
          format: date-time
      required:
        - paymentId
        - orderId
        - amount
        - status
        - paymentMethod