spring:
  application:
    name: inventory-service
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
